apiVersion: v1
kind: ServiceAccount
metadata:
  name: proxysvc-sa
  namespace: dicomproxysvc-ns
  annotations:
    iam.gke.io/gcp-service-account: eh-qa-gke-runtime-sa@prj-d-dp.iam.gserviceaccount.com